views.filter.participant_role_filter:
  type: views_filter
  label: 'Participant role'
  mapping:
    value:
      type: sequence
      label: 'Values'
      sequence:
        type: string
        label: 'Participants'
