workflows.workflow.*.third_party.workflow_participants:
  type: mapping
  label: 'Workflow transitions that participants can make'
  mapping:
    editor_transitions:
      type: sequence
      label: 'Enable editors'
      sequence:
        type: string
        label: 'Transition'
    reviewer_transitions:
      type: sequence
      label: 'Enable reviewers'
      sequence:
        type: string
        label: 'Transition'
