workflows.workflow.*.third_party.workflow_participants:
  type: mapping
  label: 'Workflow transitions that participants can make'
  mapping:
    enable_editors:
      type: sequence
      label: 'Enable editors'
      sequence:
        type: string
        label: 'Transition'
    enable_reviewers:
      type: sequence
      label: 'Enable reviewers'
      sequence:
        type: string
        label: 'Transition'
