workflows.workflow.*.third_party.workflow_participants_auto:
  type: mapping
  label: 'Users that will be added automatically on content creation'
  mapping:
    editors:
      type: sequence
      label: 'Editors'
      sequence:
        type: integer
        label: 'Editor'
    reviewers:
      type: sequence
      label: 'Reviewers'
      sequence:
        type: integer
        label: 'Reviewer'
